---
template_variables:
  book_title: VMware Tanzu Documentation
  book_title_short: VMware Tanzu Docs
  title: <span class="title-deemph">VMware Tanzu</span> Documentation
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation to help you install, understand, and succeed with VMware's enterprise-grade software."

  tile_name: Redis for VMware Tanzu Application Service
  product_url: https://network.tanzu.vmware.com/products/pivotal-cf
  product_link: <div class="header-item"><a href="https://network.tanzu.vmware.com/products/pivotal-cf">Back to Product Page</a></div>

  support_link: <a href="https://support.broadcom.com/" target="_blank">Support</a>
  support_call_to_action: <a href="https://support.broadcom.com/" target="_blank">Need Support?</a>
  support_url: https://support.broadcom.com/

  product_network: Broadcom's Customer Support Portal

  path_to_partials: /redis/partials

  api_version: 235
  gtm_account_id: GTM-MM86KCJ

  use_global_header: true
  global_header_product_href: https://network.tanzu.vmware.com/
  global_header_product_link_text: Downloads

  # VMware Tanzu Variables
  company_name: VMware
  product_full_tm: Redis for VMware Tanzu&reg; Application Service&trade;
  product_full: Redis for VMware Tanzu Application Service
  product_short: Redis for Tanzu Application Service
  product_abbr: Redis for VMware Tanzu Application Service

  app_runtime_full: VMware Tanzu Application Service for VMs
  app_runtime_abbr: TAS for VMs

  k8s_runtime_full: Tanzu Kubernetes Grid Integrated Edition
  k8s_runtime_abbr: TKGI

  windows_runtime_full: VMware Tanzu Application Service for VMs &#91;Windows&#93;
  windows_runtime_abbr: TAS for VMs &#91;Windows&#93;

  segment_runtime_full: Isolation Segment

  ops_manager: Tanzu Operations Manager

  # Pivotal variables

  platform_name: Pivotal Platform
  platform_old: Pivotal Cloud Foundry
  platform_code: PCF
  product_name_lc: pcf

  product_full_pivotal: Redis for Pivotal Platform
  product_short_pivotal: Redis for Pivotal Platform
  product_abbr_pivotal: Redis for Pivotal Platform

  product_old: Redis for Pivotal Cloud Foundry

  app_runtime_full_pivotal: Pivotal Application Service
  app_runtime_abbr_pivotal: PAS

  k8s_runtime_full_pivotal: Pivotal Container Service
  k8s_runtime_abbr_pivotal: PKS

  windows_runtime_full_pivotal: Pivotal Application Service for Windows
  windows_runtime_abbr_pivotal: PASW

  segment_runtime_full_pivotal: Pivotal Isolation Segment

  ops_manager_full: Pivotal Operations Manager

  # TAS version
  current_major_version: "5.0"
  v_major_version: "v5.0"
  dot_major_version: "5.0"
  dot_major_tas_version: "5.0"

  # Other variables

  service_name: Redis for VMware Tanzu Application Service
  service_name_article: Redis for Tanzu Application Service
  service_name_article_full: the Redis for VMware Tanzu Application Service service
  tls_prepare_overview: When you use TLS, a new port is co-located with <%= product_short %> service instances.  Apps and clients can use this secure port to establish encrypted connections with the service.
