---
template_variables:
  book_title: Pivotal Documentation
  book_title_short: Pivotal Docs
  title: <span class="title-deemph">Pivotal</span> Documentation
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation to help you install, understand, and succeed with Pivotal's enterprise-grade software."
  ops_manager: Ops Manager
  ops_manager_full: Pivotal Operations Manager
  company_name: Pivotal
  platform_name: Pivotal Platform
  platform_old: Pivotal Cloud Foundry
  platform_code: PCF
  product_name_lc: pcf
  product_name: Redis for Pivotal Platform #Do not use this in the future.
  product_full: Redis for Pivotal Platform
  product_short: Redis for Pivotal Platform
  product_abbr: Redis for Pivotal Platform
  product_old: Redis for Pivotal Cloud Foundry
  app_runtime_full: Pivotal Application Service
  app_runtime_abbr: PAS
  k8s_runtime_full: Enterprise Pivotal Container Service
  k8s_runtime_abbr: PKS
  windows_runtime_full: Pivotal Application Service for Windows
  windows_runtime_abbr: PASW
  company_name: Pivotal

  path_to_partials: /redis/partials
  product_url: https://network.pivotal.io/products/pivotal-cf
  product_link: <div class="header-item"><a href="https://network.pivotal.io/products/pivotal-cf">Back to Product Page</a></div>
  service_name: Redis for Pivotal Platform
  os_name: Redis
  tile_name: Redis
  service_name_article: Redis for Pivotal Platform
  service_name_article_full: the Redis for Pivotal Platform service
  support_link: <a href="tanzu.vmware.com/support" target="_blank">Support</a>
  support_call_to_action: <a href="tanzu.vmware.com/support" target="_blank">Need Support?</a>
  support_url: tanzu.vmware.com/support

  api_version: 235
  gtm_account_id: GTM-MM86KCJ
