---
template_variables:
  book_title: Pivotal Documentation
  book_title_short: Pivotal Docs
  title: <span class="title-deemph">Pivotal</span> Documentation
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation to help you install, understand, and succeed with VMware's enterprise-grade software."

  tile_name: Redis for VMware Tanzu Application Service
  product_url: https://network.tanzu.vmware.com/products/pivotal-cf
  product_link: <div class="header-item"><a href="https://network.tanzu.vmware.com/products/pivotal-cf">Back to Product Page</a></div>

  support_link: <a href="https://tanzu.vmware.com/support" target="_blank">Support</a>
  support_call_to_action: <a href="http://tanzu.vmware.com/support" target="_blank">Need Support?</a>
  support_url: https://tanzu.vmware.com/support

  product_network: VMware Tanzu Network

  path_to_partials: /redis/partials

  api_version: 235
  gtm_account_id: GTM-MM86KCJ

  use_global_header: true
  global_header_product_href: https://network.tanzu.vmware.com/
  global_header_product_link_text: Downloads

  # VMware Tanzu Variables
  company_name: VMware
  product_full_tm: Redis for VMware Tanzu&reg; Application Service&trade;
  product_full: Redis for VMware Tanzu Application Service
  product_short: Redis for Tanzu Application Service
  product_abbr: Redis for VMware Tanzu Application Service

  app_runtime_full: VMware Tanzu Application Service for VMs
  app_runtime_abbr: TAS for VMs

  k8s_runtime_full: Tanzu Kubernetes Grid Integrated Edition
  k8s_runtime_abbr: TKGI

  windows_runtime_full: VMware Tanzu Application Service for VMs &#91;Windows&#93;
  windows_runtime_abbr: TAS for VMs &#91;Windows&#93;

  segment_runtime_full: Isolation Segment

  ops_manager: Tanzu Operations Manager

  # Pivotal variables

  platform_name: Pivotal Platform
  platform_old: Pivotal Cloud Foundry
  platform_code: PCF
  product_name_lc: pcf
  product_name: Redis for Pivotal Platform #Do not use this in the future.
  product_full: Redis for Pivotal Platform
  product_short: Redis for Pivotal Platform
  product_abbr: Redis for Pivotal Platform
  product_old: Redis for Pivotal Cloud Foundry
  app_runtime_full: Pivotal Application Service
  app_runtime_abbr: PAS
  k8s_runtime_full: Enterprise Pivotal Container Service
  k8s_runtime_abbr: PKS
  windows_runtime_full: Pivotal Application Service for Windows
  windows_runtime_abbr: PASW
  company_name: Pivotal
  product_network: VMware Tanzu Network

  path_to_partials: /redis/partials
  product_url: https://network.tanzu.vmware.com/products/pivotal-cf
  product_link: <div class="header-item"><a href="https://network.tanzu.vmware.com/products/pivotal-cf">Back to Product Page</a></div>
  service_name: Redis for Pivotal Platform
  os_name: Redis
  tile_name: Redis
  service_name_article: Redis for Pivotal Platform
  service_name_article_full: the Redis for Pivotal Platform service
  support_link: <a href="tanzu.vmware.com/support" target="_blank">Support</a>
  support_call_to_action: <a href="tanzu.vmware.com/support" target="_blank">Need Support?</a>
  support_url: tanzu.vmware.com/support

  # TAS version
  current_major_version: "4.0"
  v_major_version: "v4.0"
  dot_major_version: "4.0"

  api_version: 235
  gtm_account_id: GTM-MM86KCJ
